cloud:
  aws:
    credentials:
      access-key:
      secret-key:
    s3:
      bucket:
    region:
      static: ap-northeast-2 # 리전 정보(서울)
    stack:
      auto: false

spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB