cloud:
  aws:
    credentials:
      access-key: AKIAVQFBB6PZUP7IPQ3Z
      secret-key: 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
    s3:
      bucket: 88hajobucket
    region:
      static: ap-northeast-2 # 리전 정보(서울)
    stack:
      auto: false

spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB